apiVersion: v1
kind: Pod
metadata:
  name: springhello
spec:
  containers:
  - image: localhost:32000/gbhat/springhello:registry
    imagePullPolicy: Always
    name: springhello
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "512Mi"
    livenessProbe:
      httpGet:
        path: /healthcheck
        port: 8080
      initialDelaySeconds: 10
      timeoutSeconds: 3
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /healthcheck
        port: 8080
      initialDelaySeconds: 30
      timeoutSeconds: 3
      periodSeconds: 10
      failureThreshold: 3
